services:
  front-end:
    build: ./front-end
    image: ${DOCKER_HUB_USERNAME}/imobiliario-frontend:latest
    ports:
      - "3000:3000"
    enviroment:
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    
    depends_on:
      - back-end

  back-end:
    build: ./back-end
    image: ${DOCKER_HUB_USERNAME}/imobiliario-backend:latest
    ports:
      - "4000:4000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_DIALECT: ${DB_DIALECT}
